name: mooTimePicker
author: marcelo.origoni
category: forms
tags: [timepicker, time, slider, forms, picker, widget, interface]
docs: http://marcelo.origoni.com.ar/mooTimePicker/
demo: http://marcelo.origoni.com.ar/mooTimePicker/demo.php
current: 1.0